version: v1

labels:
  - label: automerge
    sync: true
    required: all
    matcher:
      title: New Crowdin updates
      branch: translations
      author: paescuj
      files:
        all:
          - 'app/src/lang/translations/*.yaml'
