pull_request_rules:
  - name: Auto-approve and merge pull requests with "automerge" label
    conditions:
        - label=automerge
    actions:
      review:
        type: APPROVE
      merge:
        method: merge
