name: Auto-Merge

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - requested

jobs:
  auto-merge:
    name: Auto-Merge
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: test
        run: echo '${{ toJSON(github.event) }}'
