name: Auto-Merge Translations from Crowdin

on:
  pull_request_target:
    branches:
      - main
    # Only run if pull request includes changes in translation files
    paths:
      - 'app/src/lang/translations/*.yaml'

jobs:
  auto-merge:
    name: Auto-Merge
    # Only auto-merge if it looks like an actual pull request from Crowdin
    if: github.event.pull_request.user.login == 'paescuj' && github.event.pull_request.title == 'New Crowdin updates' && github.head_ref == 'translations'
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          do-not-merge-labels: do-not-merge
          pull-request: ${{ github.event.pull_request.id }}
      #- name: Enable auto-merge
      #  run: gh pr merge --auto --squash "$PR_URL"
      #  env:
      #    PR_URL: ${{github.event.pull_request.html_url}}
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
