name: Auto-Merge

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - requested

jobs:
  auto-merge:
    name: Auto-Merge
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: test
        run: echo '${{ toJSON(github.event) }}'
