name: Auto-Merge2
on:
  pull_request_target:
    types: [labeled]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
