name: Auto Label

on:
  pull_request_target:
  
jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - name: Label
        uses: srvaroa/labeler@master
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
