name: Auto-Merge Translations from Crowdin

on:
  pull_request:
    branches:
      - main
    # Only run if pull request includes changes in translation files
    paths:
      - 'app/src/lang/translations/*.yaml'

jobs:
  auto-merge:
    name: Auto-Merge
    # Only auto-merge if it looks like an actual pull request from Crowdin
    if: github.event.pull_request.user.login == 'paescuj' && github.event.pull_request.title == 'New Crowdin updates' && github.head_ref == 'translations'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
      #  run: gh pr merge --auto --squash "$PR_URL"
      #  env:
      #    PR_URL: ${{github.event.pull_request.html_url}}
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
