name: CI

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  post_check:
    name: Post-Check
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: actions/github-script@v5
        env:
          WORKFLOW: ${{ github.event.workflow_run }}
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: process.env.WORKFLOW.sha,
              state: 'success',
              context: 'CI / Unit Tests',
              description: 'Skipped',
            })
