name: CI - Post

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  post_check:
    name: Post-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        env:
          WORKFLOW: ${{ toJSON(github.event.workflow_run) }}
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: JSON.parse(process.env.WORKFLOW).head_sha,
              state: 'success',
              context: 'CI / Unit Tests',
              description: 'Skipped',
            })
