name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_check:
    name: Pre-Check
    runs-on: ubuntu-latest
    outputs:
      # Returns 'true' if workflow is skippable for one of the following reasons:
      # - Exact same files have been successfully checked in older run
      # - Only files that do not require checks have been changed (paths_ignore)
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      skipped_by: ${{ steps.skip_check.outputs.skipped_by }}
    steps:
        - name: Check if workflow is skippable
          id: skip_check
          uses: paescuj/skip-duplicate-actions@path-filters
          # Run all the jobs if the pre-check should fail for any reason
          # (the pre-check will be marked as 'passed', better solution pending at https://github.com/actions/toolkit/issues/399)
          continue-on-error: true
          with:
            # Cancel outdated workflow-runs
            cancel_others: 'true'
            paths_ignore: ['app/src/lang/translations/*.yaml']
            paths_filter: |
              api:
                paths:
                  - 'api/**/*'
        - name: Test output
          run: |
            echo ${{ steps.skip_check.outputs.should_skip }}
            echo ${{ steps.skip_check.outputs.reason }}
            echo ${{ steps.skip_check.outputs.skipped_by }}
            echo ${{ steps.skip_check.outputs.changed_files }}
            echo ${{ steps.skip_check.outputs.paths_result }}
        - name: Test api
          if: steps.skip_check.outputs.should_skip != 'true' && !fromJSON(steps.skip_check.outputs.paths_result).api.should_skip
          run: echo "Test api runs"

  lint:
    name: Lint
    needs: pre_check
    uses: paescuj/workflow-test/.github/workflows/lint.yml@main
    with:
      should_skip: ${{ needs.pre_check.outputs.should_skip }}

  unit_tests:
    name: Unit Tests
    needs: pre_check
    uses: paescuj/workflow-test/.github/workflows/unit-tests.yml@main
    with:
      should_skip: ${{ needs.pre_check.outputs.should_skip }}
