name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_check:
    name: Pre-Check
    runs-on: ubuntu-latest
    outputs:
      # Returns 'true' if workflow is skippable for one of the following reasons:
      # - Exact same files have been successfully checked in older run
      # - Only files that do not require checks have been changed (paths_ignore)
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      successful_duplicate: ${{ steps.skip_check.outputs.successful_duplicate }}
    steps:
      - name: Check if workflow is skippable
        id: skip_check
        uses: paescuj/skip-duplicate-actions@revision
        # Run all the jobs if the pre-check should fail for any reason
        # (the pre-check will be marked as 'passed', better solution pending at https://github.com/actions/toolkit/issues/399)
        continue-on-error: true
        with:
          # Cancel outdated workflow-runs
          cancel_others: 'true'
          paths_ignore: '["app/src/lang/translations/*.yaml"]'

  lint:
    name: Lint
    needs: pre_check
    uses: test-workflows/workflow-test/.github/workflows/lint.yml@main
    with:
      should_skip: ${{ needs.pre_check.outputs.should_skip }}

  test:
    runs-on: ubuntu-latest
    needs: pre_check
    steps:
      - run: |
        echo ${{ needs.pre_check.outputs.should_skip }}
        echo ${{ needs.pre_check.outputs.successful_duplicate.event }}
        echo ${{ github.event_name != 'push' }}
        echo ${{ needs.pre_check.outputs.should_skip == 'true' }}
        echo ${{ needs.pre_check.outputs.successful_duplicate.event == 'push' }}
        echo ${{ needs.pre_check.outputs.should_skip == 'true' && needs.pre_check.outputs.successful_duplicate.event == 'push' }}
        echo ${{ github.event_name != 'push' || (needs.pre_check.outputs.should_skip == 'true' && needs.pre_check.outputs.successful_duplicate.event == 'push') }}

  # Run end-to-end tests only on push events (on main branch) for now
  e2e_tests:
    name: End-to-End Tests
    needs: pre_check
    uses: test-workflows/workflow-test/.github/workflows/e2e-tests.yml@main
    with:
      should_skip: ${{ github.event_name != 'push' || (needs.pre_check.outputs.should_skip == 'true' && needs.pre_check.outputs.successful_duplicate.event == 'push') }}
