name: End-to-End Tests

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  test:
    name: Test
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
