name: Lint

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            console.log(context)
            console.log(github.event.workflow_run)
