name: Lint

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  lint:
    name: Lint
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  check_types_vue:
    name: Check Types in Vue Files
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check types
        shell: sh {0}
        run: |
          npx tsc --build app
          npx --yes vue-tsc --project app
