name: Unit Tests

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  test:
    name: Test
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16'
    steps:
      - run: echo ${{ matrix.node-version }}

  result:
    name: Result
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Verify job result
        if: inputs.should_skip != 'true' && needs.test.result != 'success'
        run: exit 1
