name: Unit Tests

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  test:
    name: Test
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16'
    steps:
      - run: exit 1

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: All tests succeeded
        run: echo "🎉"
