name: Unit Tests

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  test:
    name: Test
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '14'
          - '16'
    steps:
      - run: exit 0

  result:
    name: Result
    if: ${{ inputs.should_skip != 'true' && always() }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Mark result as failed
        if: needs.test.result != 'success'
        run: exit 1
