name: Unit Tests

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  test:
    name: Test (Node.js ${{ matrix.node-version }})
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
